"""empty message

Revision ID: 035e1cc47cae
Revises: 
Create Date: 2023-02-24 14:55:27.064036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035e1cc47cae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_genre', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_genre', schema=None) as batch_op:
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
